# Generated by Django 3.1.12 on 2025-03-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'Lugar',
            },
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnimal', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('lugarEncuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdjango.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Animales',
            },
        ),
    ]
